project_id = "zbtnulzvwreqzbmxulpv"

[functions.import-data]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.booking-orchestrator]
verify_jwt = false

[functions.portal-auth]
verify_jwt = false

[functions.portal-data]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.widgety-cruise]
verify_jwt = false

[functions.send-signup-otp]
verify_jwt = false

[functions.qbo-auth]
verify_jwt = false

[functions.qbo-sync]
verify_jwt = false
